### ISSUE TITLE
[bug?]自动净化

### ISSUE THREAD

**Issue by qiyi71w** [PRO-2684/LiteLoaderQQNT-pURLfy#2]
config.json 中 hooks.sendMessage 改为 true 后重启qq会自动改回false¿
是bug还是我哪里操作有问题（

**Comment by PRO-2684** [comment]
是不是修改的时候把 `shell.openExternal` 这一项删了

**Comment by qiyi71w** [comment]
> 是不是修改的时候把 `shell.openExternal` 这一项删了

不知道怎么又好了（）印象中没删吧，可能是哪里搞错了
