### ISSUE TITLE
添加中文url编码的净化

### ISSUE THREAD

**Issue by QiuShui1012** [PRO-2684/LiteLoaderQQNT-pURLfy#3]
例：
https://mzh.moegirl.org.cn/%E9%9B%8C%E5%B0%8F%E9%AC%BC#%E5%85%B8%E5%9E%8B%E5%BD%A2%E8%B1%A1
应解析为
https://mzh.moegirl.org.cn/雌小鬼#典型形象

原因：
很多中文百科的链接内会包含中文，但是并不是所有浏览器都能将其从url编码转义为中文。这导致复制的链接会被这些编码“污染”。

**Comment by PRO-2684** [comment]
很多软件（包括 qq）不会将中文字符识别为链接的一部分，所以如果进行 url 解码的话会导致链接无法识别等问题。倒是可以在设置里添加一个手动 url 解码的选项

**Comment by daizihan233** [comment]
`https://duckduckgo.com/?q=1+1`
用你的浏览器打开这个链接，看看加号会不会自动转义，这就是问题所在——许多浏览器遇到加号时会按照 HTTP 标准转义为空格而不是 `%2B`
所以这种所谓的「污染」是有必要的

个人观点

**Comment by PRO-2684** [comment]
> `https://duckduckgo.com/?q=1+1` 用你的浏览器打开这个链接，看看加号会不会自动转义，这就是问题所在——许多浏览器遇到加号时会按照 HTTP 标准转义为空格而不是 `%2B` 所以这种所谓的「污染」是有必要的
> 
> 个人观点

既然这样，被转义的空格是否有必要“净化”？是的话，发送出去后想必所有软件（以及绝大部分人）都会将其视为网址结尾；否的话，具体哪些字符需要被“净化”？

其次，查询参数内将 `/` 等字符转义以与原网址的路径进行区分是很常见的做法，这种情况下将其“净化”必然会导致部分网站出现问题。

同样的，若把被转义的 `&`, `=` 等字符 “净化”，会导致各个查询参数之间的区分出现问题。
