### ISSUE TITLE
在聊天中净化功能没有生效

### ISSUE THREAD

**Issue by youlan2333** [PRO-2684/LiteLoaderQQNT-pURLfy#4]
在聊天中净化功能没有生效，只有在插件设置中的调试才生效（p1），我想用到的是“自动净化发送的文本消息中的 URL 链接“这个功能，但是看到使用方法中”请修改 config.json 中 hooks.sendMessage 为 true”，经查找本地文件并没有config.json（p2），故前来求助
![image](https://github.com/user-attachments/assets/c669d38b-53f8-4131-82ab-13ba8e079a42)
![image](https://github.com/user-attachments/assets/5eeb73c8-a945-4061-859f-f3c993599032)
![image](https://github.com/user-attachments/assets/e4717175-e0e9-4a07-acdd-747a1d8aea1c)

**Comment by PRO-2684** [comment]
在 data/purlfy 目录下

**Comment by youlan2333** [comment]
> 在 data/purlfy 目录下

这个每次修改成true之后，重启qq又会还原成false，而且净化功能还是不行
![image](https://github.com/user-attachments/assets/ae9714dd-9152-40a0-9749-b6ac69e6e06f)
![image](https://github.com/user-attachments/assets/01f484de-080e-423e-b7fa-674c4eaa20ee)

**Comment by PRO-2684** [comment]
> > 在 data/purlfy 目录下
> 
> 这个每次修改成true之后，重启qq又会还原成false，而且净化功能还是不行 ![image](https://private-user-images.githubusercontent.com/64688148/373847703-ae9714dd-9152-40a0-9749-b6ac69e6e06f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMDY1NjYsIm5iZiI6MTcyODEwNjI2NiwicGF0aCI6Ii82NDY4ODE0OC8zNzM4NDc3MDMtYWU5NzE0ZGQtOTE1Mi00MGEwLTk3NDktYjZhYzY5ZTZlMDZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDA1MzEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ODc1ZGI0ZDg4NjAyZGQ3MWNjMGUzYWRlZWU2MzY1MjYxZDBhZWQxZWRmNmIzZGVlMWI1ZDY2MTcyZDE3N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.E08Qx-Njto4yhCnithrOuD0sGym-h0fcAMpUwmeoaSs) ![image](https://private-user-images.githubusercontent.com/64688148/373847763-01f484de-080e-423e-b7fa-674c4eaa20ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMDY1NjYsIm5iZiI6MTcyODEwNjI2NiwicGF0aCI6Ii82NDY4ODE0OC8zNzM4NDc3NjMtMDFmNDg0ZGUtMDgwZS00MjNlLWI3ZmEtNjc0YzRlYWEyMGVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDA1MzEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MDM3MmNjYjgwMTQ3MzQxN2Y2ODBmMjQwNGE5NzMwNDMxNzExNWQ0ZmY1YzIwNjcyNTM0N2Q5ZDU1Y2MxYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KsCrWzwagqtVmpfn8FslxgW4npaINmJu9Buls9lSPRc)

得退出 qq 后再修改

**Comment by youlan2333** [comment]
> > > 在 data/purlfy 目录下
> > 
> > 
> > 这个每次修改成true之后，重启qq又会还原成false，而且净化功能还是不行 ![image](https://private-user-images.githubusercontent.com/64688148/373847703-ae9714dd-9152-40a0-9749-b6ac69e6e06f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMDY1NjYsIm5iZiI6MTcyODEwNjI2NiwicGF0aCI6Ii82NDY4ODE0OC8zNzM4NDc3MDMtYWU5NzE0ZGQtOTE1Mi00MGEwLTk3NDktYjZhYzY5ZTZlMDZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDA1MzEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ODc1ZGI0ZDg4NjAyZGQ3MWNjMGUzYWRlZWU2MzY1MjYxZDBhZWQxZWRmNmIzZGVlMWI1ZDY2MTcyZDE3N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.E08Qx-Njto4yhCnithrOuD0sGym-h0fcAMpUwmeoaSs) ![image](https://private-user-images.githubusercontent.com/64688148/373847763-01f484de-080e-423e-b7fa-674c4eaa20ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMDY1NjYsIm5iZiI6MTcyODEwNjI2NiwicGF0aCI6Ii82NDY4ODE0OC8zNzM4NDc3NjMtMDFmNDg0ZGUtMDgwZS00MjNlLWI3ZmEtNjc0YzRlYWEyMGVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDA1MzEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MDM3MmNjYjgwMTQ3MzQxN2Y2ODBmMjQwNGE5NzMwNDMxNzExNWQ0ZmY1YzIwNjcyNTM0N2Q5ZDU1Y2MxYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KsCrWzwagqtVmpfn8FslxgW4npaINmJu9Buls9lSPRc)
> 
> 得退出 qq 后再修改

感谢，终于解决了
